[logging]
dump-workload = true
dump-message-contents = true

[game]
host = "purpleprison.net"
port = 25565

[experiment]
id = 7
[experiment.params]
port = "7000"
#		{ "num-bots" = "10" },
#		{ "duration" = "10m" },
#		{ "join-interval" = "1" },
#		{ "bots-per-join" = "2" },
