[logging]
dump-workload = true
dump-message-contents = true

[game]
host = "localhost"
port = 25565

[experiment]
id = 8
[experiment.params]
port = "7000"
bots = 4
#		{ "bots" = "1" },
#		{ "duration" = "10m" },
#		{ "join-interval" = "1" },
#		{ "bots-per-join" = "2" },
